In [1]:
import sqlalchemy as db
from getpass import getpass

In [2]:
password = getpass("Mysql Password: ")

Mysql Password: ········

In [3]:
dbName = "publications"
connectionData = f"mysql+pymysql://root:{password}@localhost/{dbName}"

In [4]:
engine = db.create_engine(connectionData)
print("Connected to server!")

Connected to server!

In [5]:
import pandas as pd

Challenge 1

In [6]:
df = pd.read_sql_query("""
SELECT authors.au_id AUTHORID,  titles.title, (titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100) AS ROYALTY
 
	FROM titles
	INNER JOIN titleauthor 
    on titles.title_id = titleauthor.title_id 
    INNER JOIN authors 
    on titleauthor.au_id = authors.au_id
    INNER JOIN sales 
    on sales.title_id = titles.title_id
    INNER JOIN roysched
    on titles.title_id = roysched.title_id
    order by ROYALTY desc 
""", engine)
df

        AUTHORID                     title  ROYALTY
0    238-95-7766  But Is It User Friendly?  110.160
1    238-95-7766  But Is It User Friendly?  110.160
2    238-95-7766  But Is It User Friendly?  110.160
3    238-95-7766  But Is It User Friendly?  110.160
4    238-95-7766  But Is It User Friendly?  110.160
..           ...                       ...      ...
162  899-46-2035       Is Anger the Enemy?    1.971
163  998-72-3567       Is Anger the Enemy?    1.971
164  998-72-3567       Is Anger the Enemy?    1.971
165  998-72-3567       Is Anger the Enemy?    1.971
166  998-72-3567       Is Anger the Enemy?    1.971

[167 rows x 3 columns]

In [7]:
df = pd.read_sql_query("""
SELECT authors.au_id AUTHORID,  titles.title, sum(titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100) AS ROYALTY
 
	FROM titles
	INNER JOIN titleauthor 
    on titles.title_id = titleauthor.title_id 
    INNER JOIN authors 
    on titleauthor.au_id = authors.au_id
    INNER JOIN sales 
    on sales.title_id = titles.title_id
    INNER JOIN roysched
    on titles.title_id = roysched.title_id
    group by authors.au_id,titles.title_id
    order by ROYALTY desc
""", engine)
df

       AUTHORID                                              title  ROYALTY
0   807-91-6654  Onions, Leeks, and Garlic: Cooking Secrets of ...  670.400
1   238-95-7766                           But Is It User Friendly?  550.800
2   899-46-2035                                Is Anger the Enemy?  283.824
3   998-72-3567                                Is Anger the Enemy?  283.824
4   274-80-9391                      Straight Talk About Computers  239.880
5   648-92-1872          Fifty Years in Buckingham Palace Kitchens  234.220
6   213-46-8915                    You Can Combat Computer Stress!  200.928
7   427-17-2319                          Secrets of Silicon Valley  200.000
8   846-92-7186                          Secrets of Silicon Valley  200.000
9   722-51-5454                              The Gourmet Microwave  172.224
10  756-30-7391  Computer Phobic AND Non-Phobic Individuals: Be...  161.925
11  712-45-1867                  Silicon Valley Gastronomic Treats  143.928
12  724-80-9391  Cooking with Computers: Surreptitious Balance ...  143.400
13  172-32-1176      Prolonged Data Deprivation: Four Case Studies  119.940
14  267-41-2394  Cooking with Computers: Surreptitious Balance ...   95.600
15  998-72-3567                                  Life Without Fear   70.000
16  899-46-2035                              The Gourmet Microwave   57.408
17  724-80-9391  Computer Phobic AND Non-Phobic Individuals: Be...   53.975
18  486-29-1786                Emotional Security: A New Algorithm   39.950
19  409-56-7008                The Busy Executive's Database Guide   35.982
20  672-71-3249                                     Sushi, Anyone?   35.976
21  267-41-2394                                     Sushi, Anyone?   26.982
22  472-27-2349                                     Sushi, Anyone?   26.982
23  213-46-8915                The Busy Executive's Database Guide   23.988

In [8]:
df = pd.read_sql_query("""
 SELECT authors.au_id AUTHORID, (titles.advance + sum(titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100)) AS TOTAL_PROFITS
 
	FROM titles
	INNER JOIN titleauthor 
    on titles.title_id = titleauthor.title_id 
    INNER JOIN authors 
    on titleauthor.au_id = authors.au_id
    INNER JOIN sales 
    on sales.title_id = titles.title_id
    INNER JOIN roysched
    on titles.title_id = roysched.title_id
    group by authors.au_id,titles.title_id
    order by TOTAL_PROFITS desc 
	LIMIT 3
""", engine)
df

      AUTHORID  TOTAL_PROFITS
0  722-51-5454      15172.224
1  899-46-2035      15057.408
2  213-46-8915      10325.928

Challenge 2

In [12]:
df = pd.read_sql_query("""

CREATE TEMPORARY TABLE C1(
	AUTHORID VARCHAR(30),  TITLES VARCHAR(90),  ROYALTY FLOAT(30)
 );
INSERT INTO C1
SELECT authors.au_id AUTHORID,  titles.title, sum(titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100) AS ROYALTY
 
	FROM titles
	INNER JOIN titleauthor 
    on titles.title_id = titleauthor.title_id 
    INNER JOIN authors 
    on titleauthor.au_id = authors.au_id
    INNER JOIN sales 
    on sales.title_id = titles.title_id
    INNER JOIN roysched
    on titles.title_id = roysched.title_id
    group by authors.au_id,titles.title_id
    order by ROYALTY desc
""", engine)
df

ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO C1\nSELECT authors.au_id AUTHORID,  titles.title, sum(titles.price * ' at line 4")
[SQL:

CREATE TEMPORARY TABLE C1(
	AUTHORID VARCHAR(30),  TITLES VARCHAR(90),  ROYALTY FLOAT(30)
 );
INSERT INTO C1
SELECT authors.au_id AUTHORID,  titles.title, sum(titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100) AS ROYALTY

	FROM titles
	INNER JOIN titleauthor
    on titles.title_id = titleauthor.title_id
    INNER JOIN authors
    on titleauthor.au_id = authors.au_id
    INNER JOIN sales
    on sales.title_id = titles.title_id
    INNER JOIN roysched
    on titles.title_id = roysched.title_id
    group by authors.au_id,titles.title_id
    order by ROYALTY desc
]
(Background on this error at: http://sqlalche.me/e/f405)

In [13]:
df = pd.read_sql_query("""
DROP TABLE C2;
CREATE TEMPORARY TABLE C2(
	AUTHORID VARCHAR(30),  TITLES VARCHAR(90),  ROYALTY FLOAT(30)
 );
INSERT INTO C2
   SELECT authors.au_id AUTHORID,  titles.title, sum(titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100) AS ROYALTY
 
	FROM titles
	INNER JOIN titleauthor 
    on titles.title_id = titleauthor.title_id 
    INNER JOIN authors 
    on titleauthor.au_id = authors.au_id
    INNER JOIN sales 
    on sales.title_id = titles.title_id
    INNER JOIN roysched
    on titles.title_id = roysched.title_id
    group by authors.au_id,titles.title_id
    order by ROYALTY desc 
""", engine)
df

ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TEMPORARY TABLE C2(\n\tAUTHORID VARCHAR(30),  TITLES VARCHAR(90),  ROYALTY ' at line 2")
[SQL:
DROP TABLE C2;
CREATE TEMPORARY TABLE C2(
	AUTHORID VARCHAR(30),  TITLES VARCHAR(90),  ROYALTY FLOAT(30)
 );
INSERT INTO C2
   SELECT authors.au_id AUTHORID,  titles.title, sum(titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100) AS ROYALTY

	FROM titles
	INNER JOIN titleauthor
    on titles.title_id = titleauthor.title_id
    INNER JOIN authors
    on titleauthor.au_id = authors.au_id
    INNER JOIN sales
    on sales.title_id = titles.title_id
    INNER JOIN roysched
    on titles.title_id = roysched.title_id
    group by authors.au_id,titles.title_id
    order by ROYALTY desc
]
(Background on this error at: http://sqlalche.me/e/f405)

In [14]:
df = pd.read_sql_query("""
DROP TABLE C3;
CREATE TEMPORARY TABLE C3(
	AUTHORID VARCHAR(30), TOTAL_PROFITS FLOAT(30)
 );
INSERT INTO C3
	SELECT authors.au_id AUTHORID, (titles.advance + sum(titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100)) AS TOTAL_PROFITS
 
	FROM titles
	INNER JOIN titleauthor 
    on titles.title_id = titleauthor.title_id 
    INNER JOIN authors 
    on titleauthor.au_id = authors.au_id
    INNER JOIN sales 
    on sales.title_id = titles.title_id
    INNER JOIN roysched
    on titles.title_id = roysched.title_id
    group by authors.au_id,titles.title_id
    order by TOTAL_PROFITS desc 
	LIMIT 3; 
""", engine)
df

ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TEMPORARY TABLE C3(\n\tAUTHORID VARCHAR(30), TOTAL_PROFITS FLOAT(30)\n );\nIN' at line 2")
[SQL:
DROP TABLE C3;
CREATE TEMPORARY TABLE C3(
	AUTHORID VARCHAR(30), TOTAL_PROFITS FLOAT(30)
 );
INSERT INTO C3
	SELECT authors.au_id AUTHORID, (titles.advance + sum(titles.price * sales.qty * titles.royalty / 100 * titleauthor.royaltyper / 100)) AS TOTAL_PROFITS

	FROM titles
	INNER JOIN titleauthor
    on titles.title_id = titleauthor.title_id
    INNER JOIN authors
    on titleauthor.au_id = authors.au_id
    INNER JOIN sales
    on sales.title_id = titles.title_id
    INNER JOIN roysched
    on titles.title_id = roysched.title_id
    group by authors.au_id,titles.title_id
    order by TOTAL_PROFITS desc
	LIMIT 3;
]
(Background on this error at: http://sqlalche.me/e/f405)

Challenge 3

In [15]:
df = pd.read_sql_query("""
DROP TABLE CFINAL;
CREATE TABLE CFINAL(AUTHORID VARCHAR(30), TOTALPROFITS FLOAT(30)
);
INSERT INTO CFINAL
	SELECT * FROM C3;
""", engine)
df

ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE CFINAL(AUTHORID VARCHAR(30), TOTALPROFITS FLOAT(30)\n);\nINSERT INTO ' at line 2")
[SQL:
DROP TABLE CFINAL;
CREATE TABLE CFINAL(AUTHORID VARCHAR(30), TOTALPROFITS FLOAT(30)
);
INSERT INTO CFINAL
	SELECT * FROM C3;
]
(Background on this error at: http://sqlalche.me/e/f405)

In [ ]:
## En el 3er challenge entendí que tenía que haber hecho en todo el 2do challenge :(
## Me ha costado bastante estos labs y la verdad que he aprendido a base de errores y poder ver que mis compañeros también..
## han tenido dificultades y poder ir echandonos una mano con planteamientos