In [2]:
import pandas as pd
import sqlalchemy as db
from getpass import getpass

In [3]:
user = "root"
password = getpass("Insert password: ")

Insert password: ········

In [4]:
connectionURI = f"mysql+pymysql://{user}:{password}@localhost/publications"

In [5]:
engine = db.create_engine(connectionURI)
print("Connected to server!")

Connected to server!

In [6]:
#Part 1

d0 = pd.read_sql_query("""SELECT ta.au_id AUTHOR_ID, ta.title_id TITLE_ID, ROUND(t.price * s.qty *t.royalty/100 * t.royalty/100,2) SALES_ROYALTY
FROM titleauthor ta
	LEFT JOIN titles t ON t.title_id = ta.title_id
    LEFT JOIN sales s ON s.title_id = t.title_id
    ;""",engine)
d0

      AUTHOR_ID TITLE_ID  SALES_ROYALTY
0   213-46-8915   BU1032           1.00
1   213-46-8915   BU1032           2.00
2   409-56-7008   BU1032           1.00
3   409-56-7008   BU1032           2.00
4   267-41-2394   BU1111           2.99
5   724-80-9391   BU1111           2.99
6   213-46-8915   BU2075           6.03
7   274-80-9391   BU7832           3.00
8   712-45-1867   MC2222           2.88
9   722-51-5454   MC3021           4.31
10  722-51-5454   MC3021           2.58
11  899-46-2035   MC3021           4.31
12  899-46-2035   MC3021           2.58
13  238-95-7766   PC1035          17.63
14  427-17-2319   PC8888          10.00
15  846-92-7186   PC8888          10.00
16  486-29-1786   PC9999            NaN
17  724-80-9391   PS1372           4.32
18  756-30-7391   PS1372           4.32
19  899-46-2035   PS2091           0.47
20  899-46-2035   PS2091          11.83
21  899-46-2035   PS2091           1.58
22  899-46-2035   PS2091           3.15
23  998-72-3567   PS2091           0.47
24  998-72-3567   PS2091          11.83
25  998-72-3567   PS2091           1.58
26  998-72-3567   PS2091           3.15
27  998-72-3567   PS2106           1.75
28  172-32-1176   PS3333           3.00
29  486-29-1786   PS7777           2.00
30  807-91-6654   TC3218           8.38
31  648-92-1872   TC4203           4.68
32  267-41-2394   TC7777           3.00
33  472-27-2349   TC7777           3.00
34  672-71-3249   TC7777           3.00

In [7]:
#Part 2

d1 = pd.read_sql_query("""SELECT AUTHOR_ID, TITLE_ID, SUM(SALES_ROYALTY)

FROM( SELECT ta.au_id AUTHOR_ID, ta.title_id TITLE_ID, ROUND(t.price * s.qty *t.royalty/100 * t.royalty/100,2) SALES_ROYALTY
FROM titleauthor ta
LEFT JOIN titles t ON t.title_id = ta.title_id
LEFT JOIN sales s ON s.title_id = t.title_id) AS total
    ;""",engine)
d0

InternalError: (pymysql.err.InternalError) (1140, "In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'total.AUTHOR_ID'; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT AUTHOR_ID, TITLE_ID, SUM(SALES_ROYALTY)

FROM( SELECT ta.au_id AUTHOR_ID, ta.title_id TITLE_ID, ROUND(t.price * s.qty *t.royalty/100 * t.royalty/100,2) SALES_ROYALTY
FROM titleauthor ta
LEFT JOIN titles t ON t.title_id = ta.title_id
LEFT JOIN sales s ON s.title_id = t.title_id) AS total
    ;]
(Background on this error at: http://sqlalche.me/e/2j85)