In [13]:
import sqlalchemy as db
import getpass

In [16]:
user = "root"
password = getpass.getpass("Insert password: ")

Insert password: ········

In [47]:
connectionURI = f"mysql+pymysql://{user}:{password}@localhost/my_sql"
engine = db.create_engine(connectionURI)
print("Connected to server!")

Connected to server!

# Challenge 1 - Who Have Published What At Where?

In [49]:
import pandas as pd

df = pd.read_sql_query("""SELECT au.au_id as "AUTHOR ID", au.au_lname as "LAST NAME", au.au_fname as "FIRST NAME", t.title as"TITLE", pub.pub_id as "PUBLISHER"
 FROM authors AS au
INNER JOIN titleauthor as ta 
ON au.au_id=ta.au_id
INNER JOIN titles as t
ON ta.title_id=t.title_id
INNER JOIN publishers as pub
ON t.pub_id=pub.pub_id;""", engine)
df

,AUTHOR ID,LAST NAME,FIRST NAME,TITLE,PUBLISHER
0,213-46-8915,Green,Marjorie,The Busy Executive's Database Guide,1389
1,409-56-7008,Bennet,Abraham,The Busy Executive's Database Guide,1389
2,267-41-2394,O'Leary,Michael,Cooking with Computers: Surreptitious Balance ...,1389
3,724-80-9391,MacFeather,Stearns,Cooking with Computers: Surreptitious Balance ...,1389
4,213-46-8915,Green,Marjorie,You Can Combat Computer Stress!,0736
5,274-80-9391,Straight,Dean,Straight Talk About Computers,1389
6,712-45-1867,del Castillo,Innes,Silicon Valley Gastronomic Treats,0877
7,722-51-5454,DeFrance,Michel,The Gourmet Microwave,0877
8,899-46-2035,Ringer,Anne,The Gourmet Microwave,0877
9,238-95-7766,Carson,Cheryl,But Is It User Friendly?,1389
10,427-17-2319,Dull,Ann,Secrets of Silicon Valley,1389
11,846-92-7186,Hunter,Sheryl,Secrets of Silicon Valley,1389
12,486-29-1786,Locksley,Charlene,Net Etiquette,1389
13,724-80-9391,MacFeather,Stearns,Computer Phobic AND Non-Phobic Individuals: Be...,0877
14,756-30-7391,Karsen,Livia,Computer Phobic AND Non-Phobic Individuals: Be...,0877
15,899-46-2035,Ringer,Anne,Is Anger the Enemy?,0736
16,998-72-3567,Ringer,Albert,Is Anger the Enemy?,0736
17,998-72-3567,Ringer,Albert,Life Without Fear,0736
18,172-32-1176,White,Johnson,Prolonged Data Deprivation: Four Case Studies,0736
19,486-29-1786,Locksley,Charlene,Emotional Security: A New Algorithm,0736
20,807-91-6654,Panteley,Sylvia,"Onions, Leeks, and Garlic: Cooking Secrets of ...",0877
21,648-92-1872,Blotchet-Halls,Reginald,Fifty Years in Buckingham Palace Kitchens,0877
22,267-41-2394,O'Leary,Michael,"Sushi, Anyone?",0877
23,472-27-2349,Gringlesby,Burt,"Sushi, Anyone?",0877
24,672-71-3249,Yokomoto,Akiko,"Sushi, Anyone?",0877

# Challenge 2 - Who Have Published How Many At Where?

In [52]:
df2 = pd.read_sql_query("""SELECT au.au_id as "AUTHOR ID", au.au_lname as "LAST NAME", au.au_fname as "FIRST NAME", t.title as"TITLE", pub.pub_id as "PUBLISHER",count(t.title ) as "TITLE COUNT"
 FROM authors AS au
INNER JOIN titleauthor as ta 
ON au.au_id=ta.au_id
INNER JOIN titles as t
ON ta.title_id=t.title_id
INNER JOIN publishers as pub
ON t.pub_id=pub.pub_id
GROUP BY au.au_id,au.au_lname,au.au_fname,t.title,pub.pub_id;""", engine)
df2

,AUTHOR ID,LAST NAME,FIRST NAME,TITLE,PUBLISHER,TITLE COUNT
0,213-46-8915,Green,Marjorie,The Busy Executive's Database Guide,1389,1
1,409-56-7008,Bennet,Abraham,The Busy Executive's Database Guide,1389,1
2,267-41-2394,O'Leary,Michael,Cooking with Computers: Surreptitious Balance ...,1389,1
3,724-80-9391,MacFeather,Stearns,Cooking with Computers: Surreptitious Balance ...,1389,1
4,213-46-8915,Green,Marjorie,You Can Combat Computer Stress!,0736,1
5,274-80-9391,Straight,Dean,Straight Talk About Computers,1389,1
6,712-45-1867,del Castillo,Innes,Silicon Valley Gastronomic Treats,0877,1
7,722-51-5454,DeFrance,Michel,The Gourmet Microwave,0877,1
8,899-46-2035,Ringer,Anne,The Gourmet Microwave,0877,1
9,238-95-7766,Carson,Cheryl,But Is It User Friendly?,1389,1
10,427-17-2319,Dull,Ann,Secrets of Silicon Valley,1389,1
11,846-92-7186,Hunter,Sheryl,Secrets of Silicon Valley,1389,1
12,486-29-1786,Locksley,Charlene,Net Etiquette,1389,1
13,724-80-9391,MacFeather,Stearns,Computer Phobic AND Non-Phobic Individuals: Be...,0877,1
14,756-30-7391,Karsen,Livia,Computer Phobic AND Non-Phobic Individuals: Be...,0877,1
15,899-46-2035,Ringer,Anne,Is Anger the Enemy?,0736,1
16,998-72-3567,Ringer,Albert,Is Anger the Enemy?,0736,1
17,998-72-3567,Ringer,Albert,Life Without Fear,0736,1
18,172-32-1176,White,Johnson,Prolonged Data Deprivation: Four Case Studies,0736,1
19,486-29-1786,Locksley,Charlene,Emotional Security: A New Algorithm,0736,1
20,807-91-6654,Panteley,Sylvia,"Onions, Leeks, and Garlic: Cooking Secrets of ...",0877,1
21,648-92-1872,Blotchet-Halls,Reginald,Fifty Years in Buckingham Palace Kitchens,0877,1
22,267-41-2394,O'Leary,Michael,"Sushi, Anyone?",0877,1
23,472-27-2349,Gringlesby,Burt,"Sushi, Anyone?",0877,1
24,672-71-3249,Yokomoto,Akiko,"Sushi, Anyone?",0877,1

# Challenge 3 - Best Selling Authors

In [63]:
df3 = pd.read_sql_query("""SELECT au.au_id as "AUTHOR ID", au.au_lname as "LAST NAME", au.au_fname as "FIRST NAME", sum(s.qty) as "TOTAL SALES"
 FROM authors AS au
INNER JOIN titleauthor as ta 
ON au.au_id=ta.au_id
INNER JOIN sales as s
ON ta.title_id=s.title_id
GROUP BY au.au_id,au.au_lname,au.au_fname
ORDER BY sum(s.qty) DESC LIMIT 3;""",engine)
df3

     AUTHOR ID LAST NAME FIRST NAME  TOTAL SALES
0  899-46-2035    Ringer       Anne        148.0
1  998-72-3567    Ringer     Albert        133.0
2  213-46-8915     Green   Marjorie         50.0

# Challenge 4 - Best Selling Authors Ranking

In [64]:
df4 = pd.read_sql_query("""SELECT au.au_id as "AUTHOR ID", au.au_lname as "LAST NAME", au.au_fname as "FIRST NAME", IFNULL(sum(s.qty),0) as "TOTAL SALES"
 FROM authors AS au
INNER JOIN titleauthor as ta 
ON au.au_id=ta.au_id
INNER JOIN sales as s
ON ta.title_id=s.title_id
GROUP BY au.au_id,au.au_lname,au.au_fname
ORDER BY sum(s.qty) desc;""", engine)
df4

      AUTHOR ID       LAST NAME FIRST NAME  TOTAL SALES
0   899-46-2035          Ringer       Anne        148.0
1   998-72-3567          Ringer     Albert        133.0
2   213-46-8915           Green   Marjorie         50.0
3   427-17-2319            Dull        Ann         50.0
4   846-92-7186          Hunter     Sheryl         50.0
5   267-41-2394         O'Leary    Michael         45.0
6   724-80-9391      MacFeather    Stearns         45.0
7   807-91-6654        Panteley     Sylvia         40.0
8   722-51-5454        DeFrance     Michel         40.0
9   238-95-7766          Carson     Cheryl         30.0
10  486-29-1786        Locksley   Charlene         25.0
11  648-92-1872  Blotchet-Halls   Reginald         20.0
12  472-27-2349      Gringlesby       Burt         20.0
13  672-71-3249        Yokomoto      Akiko         20.0
14  756-30-7391          Karsen      Livia         20.0
15  409-56-7008          Bennet    Abraham         15.0
16  172-32-1176           White    Johnson         15.0
17  274-80-9391        Straight       Dean         15.0
18  712-45-1867    del Castillo      Innes         10.0